library(rsconnect)
#USER INPUT REQUIRED
#UPDATE APP DIRECTORY USING LOCAL DIRECTORY, WHICH INCLUDES YOUR SHINY.IO RSCONNECT AUTHENTICATION TOKEN AND YOUR GOOGLE SHEETS .secrets AUTHENICATION TOKEN.
rsconnect::deployApp("Your_directory/file_path_here")

#overwrite option
y
